### ISSUE TITLE
Maintainer Access to `go-zenon`

### ISSUE THREAD

**Issue by 0x3639** [zenon-network/go-zenon#24]
@georgezgeorgez @sumamu @MoonBaZZe 

I think we should have a process to add / remove maintainers from repos.  In particular the go-zenon repo.  It appears I have the ability to add maintainers.  

How do you guys feel about this process? If someone wants to be added as a maintainer, they can submit a request for access in a GH issue.  For now, we could require 100% of maintainers to approve the addition of new maintainers by responding yes in the GH issue. 

Thoughts?

**Comment by sumamu** [comment]
I agree. If we have the ability we should use it.
