### ISSUE TITLE
no valid genesis file. Reason: 'invalid genesis config. Failed to pass tests'. Stopping ...

### ISSUE THREAD

**Issue by samsondav** [zenon-network/go-zenon#7]
Can't run latest version, even with a valid genesis.json I see this error:

```
no valid genesis file. Reason: 'invalid genesis config. Failed to pass tests'. Stopping ...
```

**Comment by dumeriz** [comment]
> Can't run latest version, even with a valid genesis.json I see this error:
> 
> 
> 
> ```
> 
> no valid genesis file. Reason: 'invalid genesis config. Failed to pass tests'. Stopping ...
> 
> ```

I think the reason here was that the current version receives the genesis from the network or other sources. Try to remove the genesis.json file from the config folder and also the entry specifying the genesis file from the configuration json file.
